== JavaScript (ES2015)

Antes de ponernos manos a la obra deberíamos repasar JavaScript ya que va a
ser el lenguaje que nos va a acompañar durante todo el desarrollo de la
aplicación web.

Vamos a hacer incapié en las nuevas funcionalidades definidas
en el estándar ES2015, que pasan desapercibidas en la asignatura, a pesar de
mejorar mucho el lenguaje.

Aunque existen versiones más modernas aún, todavía no están completamente
soportadas en la mayoría de los navegadores.

=== Declaración de variables

Tradicionalmente en JavaScript se ha usado el _keyword_ `var` para la
declaración de variables. Declarar variables de esta forma tiene algunas
peculiaridades que nos puede inducir a errores en nuestro código, por lo que
*no deberíamos usar `var`* jamás.

.Declarando variable con `var`
[source, javascript]
----
console.log(nombre);
var nombre = 'Carlos';
----

Parece un error obvio, y de hecho lo es. Sin embargo, errores
como este ocurren a menudo y la mayoría de las veces (cuando hay miles de
líneas de código) no son para nada obvios. En otros lenguajes esperaríamos que
este código de algún tipo de error, puesto que claramente estamos usando la
variable `nombre` antes de ser declarada. Desgraciadamente, JavaScript
(debido a una funcionalidad conocida como _hoisting_) convierte el código
anterior internamente en el siguiente:

.Hoisting en JavaScript
====
[source, javascript]
----
var nombre;
console.log(nombre);
nombre = 'Carlos';
----
----
undefined
----
====

Por lo tanto, este código no dará ningún error y funcionará. Sin embargo,
funcionará haciendo *algo que no es lo que esperamos*, lo cual es mucho peor.
En este caso el programa imprimirá `undefined`, ya que la variable ha sido
declarada pero no tiene asignado un valor.

CAUTION: En la programación siempre se prefiere un programa que no funcione
antes que un programa que funcione de forma inesperada.

Presentando *`let`* y *`const`*. Declarando una variable usando `let` en lugar
de `var` evita este problema ya que sí dará un error al ejecutarlo y no
tendremos un comportamiento inesperado.

.Declarando con `let`
====
[source, javascript]
----
console.log(nombre);
let nombre = 'Carlos';
----
----
ReferenceError: nombre is not defined
----
====

Otro caso en el que `var` nos la puede jugar es el siguiente:

.Alcance de `var`
[source, javascript]
----
function varTest(condicion) {
  var x = 31;

  if (condicion) {
    var x = 71;
    console.log(x); <1>
  }

  console.log(x); <2>
}
----

<1> Aquí se imprimiría por pantalla `71`
<2> ¡Aquí también se imprimiría por pantalla `71`!

En este caso hemos declarado una variable dentro del bloque `if` con el mismo
nombre que una de fuera. En la mayoría de los lenguajes se produciría lo que se
conoce como _shadowing_, es decir, que dejaríamos de ver la variable `x` de
fuera y tendríamos una `x` local, por lo que si modificamos su valor, la `x` de
fuera quedaría intacta. *No es el caso de `var`*. En este caso habríamos
cambiado el valor de la variable `x`. Una vez más, usando `let` nos ahorraríamos
este tipo de comportamientos que nos conducen a errores.

.Alcance de `let`
[source, javascript]
----
function varTest(condicion) {
  let x = 31;

  if (condicion) {
    let x = 71;
    console.log(x); <1>
  }

  console.log(x); <2>
}
----

<1> Aquí se imprimiría por pantalla `71`
<2> Aquí se imprimiría por pantalla `31`

`const` tiene las mismas propiedades que `let`, pero además nos impide reasignar
la variable, lo cual nos da un plus de seguridad. Por regla general deberíamos
declarar todo usando `const` y *sólamente cuando sea completamente necesario*
usar `let`.

.Usando `const`
====
[source, javascript]
----
const nombre = 'Carlos';
nombre = `Ernesto`;
----
----
TypeError: Assignment to constant variable.
----
====

CAUTION: Nunca declarar variables con `var`.

=== Triple igual `===`

Cuando se empieza con JavaScript un error que se suele cometer es pensar que el
doble igual `==` para las comparaciones es equivalente al doble igual visto en
otros lenguajes. Esto no es así. En JavaScript tenemos el triple igual `===` que
es el equivalente al doble igual en los otros lenguajes. ¿Cuál es la diferencia?

.Doble igual
[source, javascript]
----
null == undefined;
0 == '';
0 == [];
0 == false;
'' == [];
----

Aparentemente estamos comparando cosas completamente diferentes, sin embargo,
todos los casos anteriores devuelven `true`. Por supuesto, esto es otra fuente
muy común de errores que puede dar muchos dolores de cabeza. En cambio, usando
el triple igual, todos los casos anteriores son `false`.

CAUTION: Nunca usar el operador doble igual `==`.

=== Flecha gorda (_fat arrow_)

En JavaScript es muy común encontrarnos con el siguiente patrón:

.Pasando una función como parámetro
[source, javascript]
----
const fs = require('fs'); <1>

fs.readFile('/home/carlos/fichero', 'utf8', function(err, data) { <2>
  if (err) {
    return console.log(err);
  }

  console.log(data);
});

const plusOne = function(number) {
  return number + 1;
}

plusOne(7); <3>
----

<1> Importamos el módulo `fs` de Node.js que se usa para leer ficheros.
<2> Pasamos una función como parámetro.
<3> Devuelve 8.

En este caso, le estamos pasando a la función `fs.readFile` tres parámetros,
los dos primeros son de tipo _string_ y el segundo es una función lambda.

Este patrón es típico en JavaScript, básicamente consiste en definir una
función, pero en lugar de llamarla nosotros, la pasamos a `fs.readFile` para que
la llame cuando haya terminado de leer el fichero. Cuando usamos una función
de esta forma le llamamos *función _callback_*. Nosotros nunca llamamos a la
función _callback_, sino que la llama la función a la cual se la hemos pasado.
De hecho, no podríamos llamarla aunque quisíeramos porque es una función
anónima.

NOTE: Las funciones lambda son aquellas que definen y pasan como parámetro a
otra función en su llamada. No es una definición muy rigurosa, pero para este
caso es suficiente.

Esta notación es tan frecuente en JavaScript que en la versión ES2015 tenemos
una forma compacta de escribirla, conocida como notación _fat arrow_:

.Fat arrow
[source, javascript]
----
const fs = require('fs');

fs.readFile('/home/carlos/fichero', 'utf8', (err, data) => {
  if (err) {
    return console.log(err);
  }

  console.log(data);
});

const plusOne = number => number + 1;
plusOne(7);
----

En el caso de la función `plusOne` vemos que se ha quedado aún más compacta
porque la notación _fat arrow_ permite lo siguiente:

* Cambiar `function(arg1, arg2, arg3) { ... }` por
  `(arg1, arg2, arg3) => { ... }`
* Si hay un sólo parámetro se pueden omitir los paréntesis `arg => { ... }`
* Si la función sólo tiene una línea que es un `return`, se puede eliminar el
`return` y las llaves: `arg => {return 1}` quedaría como `arg => 1`.

Otra situación que tradicionalmente ha sido muy molesta en JavaScript era la
siguiente:

.Pérdida de la referencia a `this`
[source, javascript]
----
const Alumno = function(nombre) {
  this.nombre = nombre;
}

Alumno.prototype.mostrarNota = function() {
  const self = this; <1>
  obtenerNota(function(nota) {
    console.log('La nota de ' + self.nombre + ' es :' + nota);
  });
}

const carlos = new Alumno('Carlos');
carlos.mostrarNota();
----

<1> Guardamos la referencia a `this` en `self`.

En el código anterior queremos usar el atributo `nombre` de la clase `Alumno`,
pero no podemos usar la referencia `this` dentro de una función _callback_ ya
que `this` en este contexto se refiere a la función _callback_ y no a la
instancia de `Alumno`. Esto siempre ha sido una molestia hasta la llegada de la
función _fat arrow_. Con ella podemos escribir el mismo código de la siguiente
forma:

.Uso de _fat arrow_ con `this`
[source, javascript]
----
const Alumno = function(nombre) {
  this.nombre = nombre;
}

Alumno.prototype.mostrarNota = function() {
  obtenerNota(nota => console.log('La nota de ' + this.nombre + ' es :' + nota));
}

const carlos = new Alumno('Carlos');
carlos.mostrarNota();
----

Como vemos, la notación _fat arrow_ no sobrescribe la referencia a `this`.

CAUTION: Usar la notación _fat arrow_ siempre que la usemos como una función
lambda. De hecho, muchas veces se le llama lambda a las funciones definidas
usando la notación _fat arrow_.

=== Interpolación

JavaScript, al ser un lenguaje con un tipado débil, permite realizar operaciones
entre tipos que pueden no tener sentido. Para los números, está definida la
suma, la resta, la multipliación, etc. La confusión viene cuando hacemos cosas
como sumar enteros con cadenas, sumar arrays con objetos, restar `null` a
números, etc.

En JavaScript ES2015 tenemos la interpolación de cadenas. Esto es, una forma de
definir una cadena usando los caracteres ``` en lugar de comillas simples o
dobles. Usando método podemos usar variables dentro de cualquier cadena sin
tener que usar el operador suma para concatenarlas.

.Interpolación de cadenas
[source, javascript]
----
const nombre = 'Carlos'
const apellido = 'Fernández'
const edad = 31

console.log(
  'Hola, me llamo ' + nombre + ' ' + apellido + ' y tengo ' + edad + ' años.',
)
console.log(`Hola, me llamo ${nombre} ${apellido} y tengo ${edad} años.`)
----

Las dos formas anteriores son equivalentes. La segunda forma, además de ser más
limpia, es más segura al no usar el operador `+` que muchas veces da resultados
inesperados.

CAUTION: Nunca usar el operador `+` entre diferentes tipos y preferir siempre
la interpolación a la concatenación.

=== Clases

JavaScript no tiene clases, no nos engañemos. En lugar de clases tiene un
sistema de prototipos. Todos los objetos se crean a partir de un prototipo, por
lo que si modificamos el prototipo, los objetos creados a partir de éste también
portarán los cambios.

Técnicamente el sistema de prototipos es más potente que el sistema de clases,
ya que el sistema de prototipos permite "emular" el sistema de clases, pero no
al revés. Con la popularidad que ha adquirido el paradigma de orientación
a objetos, es muy típico usar JavaScript orientado a objetos, aunque su
sintaxis no es la más limpia. Veamos un ejemplo:

[[clases-antiguas]]
.Clases en JavaScript pre-ES2015
====
[source, javascript]
----
// Constructor de la clase Alumno
function Alumno(_nombre, _edad) {

  // Atributos privados
  let edad = _edad

  // Atributos públicos
  this.nombre = _nombre

  // Método privado
  function sumaEdad(años) {
    edad += años
  }

  // Método público
  this.cumpleAños = function() {
    sumaEdad(1)
    console.log(`Me llamo ${this.nombre} y he cumplido ${edad} años!`)
  }
}

const carlos = new Alumno('Carlos', 31)
carlos.cumpleAños()
----
----
Me llamo Carlos y he cumplido 32 años!
----
====

Como hemos dicho, no es lo más bonito del mundo, pero funciona. En las nuevas
versiones de JavaScript tenemos una forma mucho más elegante para definir
clases.

.Creando clases en JavaScript ES2015
[source, javascript]
----
class Alumno {
  constructor(nombre, edad) {
    this.nombre = nombre
    this.edad = edad
  }

  sumaEdad(años) {
    this.edad += años
  }

  cumpleAños() {
    this.sumaEdad(1)
    console.log(`Me llamo ${this.nombre} y he cumplido ${this.edad} años!`)
  }
}

const carlos = new Alumno('Carlos', 31)
carlos.cumpleAños()
----

Como vemos es mucho más elegante usar esta sintaxis. Sin embargo, hemos perdido
la capacidad de declarar métodos y atributos privados. Esto es un problema
que podrá solucionarse en futuras versiones de JavaScript. Por ahora si
necesitamos atributos o métodos privados, debemos recurrir a la sintaxis
antigua.

WARNING: Recuerdo que en JavaScript no existen las clases. El código anterior,
a pesar de usar el _keyword_ `class`, internamente se convierte al código que
hemos visto en <<clases-antiguas>>
